# Dataset loading examples

In [1]:
from ThreeWToolkit.dataset import ParquetDatasetConfig

## Download from figshare if not on local yet

If the dataset is not found at the given `path`, it will be downloaded automatically.

If you use `force_download=True`, the dataset will be downloaded regardless of whether it already exists locally. If it exists locally, it will be replaced by the new one. `force_download` defaults to `False`.


It may take a while to download from figshare (1.79GB) takes about 2-3 minutes to download.

Only dataset v2.0.0 is supported.

In [2]:
# Modify this path to the folder where your dataset is downloaded
dataset_path = "../../dataset"

In [3]:
# Load all files, selecting two classes (0 and 4), build() class from the ParquetDatasetConfig config.
ds = ParquetDatasetConfig(path=dataset_path, target_class=[0, 4]).build()

2026-04-06 13:18:23,046 | INFO | ThreeWToolkit.dataset.parquet_dataset | Dataset found at ../../dataset
2026-04-06 13:18:23,047 | INFO | ThreeWToolkit.dataset.parquet_dataset | Validating dataset integrity...
2026-04-06 13:18:23,048 | INFO | ThreeWToolkit.dataset.parquet_dataset | Dataset integrity check passed!

Get the number of events:

In [4]:
print(f"Dataset size: {len(ds)}")

Dataset size: 937

## Signal and label split

Our dataset object is a list of DatasetOutputs object, found at the Core directory in our toolkit.

Let's see the components of the first element (Each event is a single DatasetOutputs).

This object contains "signal", "label" and a "metadata" field.

In [5]:
ds[0]

DatasetOutputs(signal=                     ABER-CKGL  ABER-CKP  ESTADO-DHSV  ESTADO-M1  ESTADO-M2  \
timestamp
2017-02-01 01:02:07        NaN       NaN          1.0        1.0        0.0
2017-02-01 01:02:08        NaN       NaN          1.0        1.0        0.0
2017-02-01 01:02:09        NaN       NaN          1.0        1.0        0.0
2017-02-01 01:02:10        NaN       NaN          1.0        1.0        0.0
2017-02-01 01:02:11        NaN       NaN          1.0        1.0        0.0
...                        ...       ...          ...        ...        ...
2017-02-01 06:59:56        NaN       NaN          1.0        1.0        0.0
2017-02-01 06:59:57        NaN       NaN          1.0        1.0        0.0
2017-02-01 06:59:58        NaN       NaN          1.0        1.0        0.0
2017-02-01 06:59:59        NaN       NaN          1.0        1.0        0.0
2017-02-01 07:00:00        NaN       NaN          1.0        1.0        0.0

                     ESTADO-PXO  ESTADO-SDV-GL  ESTADO-SDV-P  ESTADO-W1  \
timestamp
2017-02-01 01:02:07         0.0            0.0           1.0        1.0
2017-02-01 01:02:08         0.0            0.0           1.0        1.0
2017-02-01 01:02:09         0.0            0.0           1.0        1.0
2017-02-01 01:02:10         0.0            0.0           1.0        1.0
2017-02-01 01:02:11         0.0            0.0           1.0        1.0
...                         ...            ...           ...        ...
2017-02-01 06:59:56         0.0            0.0           1.0        1.0
2017-02-01 06:59:57         0.0            0.0           1.0        1.0
2017-02-01 06:59:58         0.0            0.0           1.0        1.0
2017-02-01 06:59:59         0.0            0.0           1.0        1.0
2017-02-01 07:00:00         0.0            0.0           1.0        1.0

                     ESTADO-W2  ...  P-PDG  PT-P       P-TPT  QBS  QGL  \
timestamp                       ...
2017-02-01 01:02:07        0.0  ...    0.0   NaN  10074540.0  NaN  0.0
2017-02-01 01:02:08        0.0  ...    0.0   NaN  10074540.0  NaN  0.0
2017-02-01 01:02:09        0.0  ...    0.0   NaN  10074540.0  NaN  0.0
2017-02-01 01:02:10        0.0  ...    0.0   NaN  10074540.0  NaN  0.0
2017-02-01 01:02:11        0.0  ...    0.0   NaN  10074540.0  NaN  0.0
...                        ...  ...    ...   ...         ...  ...  ...
2017-02-01 06:59:56        0.0  ...    0.0   NaN  10014690.0  NaN  0.0
2017-02-01 06:59:57        0.0  ...    0.0   NaN  10014690.0  NaN  0.0
2017-02-01 06:59:58        0.0  ...    0.0   NaN  10014690.0  NaN  0.0
2017-02-01 06:59:59        0.0  ...    0.0   NaN  10014690.0  NaN  0.0
2017-02-01 07:00:00        0.0  ...    0.0   NaN  10014690.0  NaN  0.0

                     T-JUS-CKP  T-MON-CKP  T-PDG     T-TPT  state
timestamp
2017-02-01 01:02:07   84.64463        NaN    0.0  119.0781   <NA>
2017-02-01 01:02:08   84.63828        NaN    0.0  119.0781   <NA>
2017-02-01 01:02:09   84.63194        NaN    0.0  119.0781   <NA>
2017-02-01 01:02:10   84.62558        NaN    0.0  119.0781   <NA>
2017-02-01 01:02:11   84.61923        NaN    0.0  119.0781   <NA>
...                        ...        ...    ...       ...    ...
2017-02-01 06:59:56   83.44021        NaN    0.0  119.0453      0
2017-02-01 06:59:57   83.45413        NaN    0.0  119.0452      0
2017-02-01 06:59:58   83.46806        NaN    0.0  119.0451      0
2017-02-01 06:59:59   83.48199        NaN    0.0  119.0450      0
2017-02-01 07:00:00   83.49591        NaN    0.0  119.0449      0

[21474 rows x 28 columns], label=timestamp
2017-02-01 01:02:07    <NA>
2017-02-01 01:02:08    <NA>
2017-02-01 01:02:09    <NA>
2017-02-01 01:02:10    <NA>
2017-02-01 01:02:11    <NA>
                       ...
2017-02-01 06:59:56       0
2017-02-01 06:59:57       0
2017-02-01 06:59:58       0
2017-02-01 06:59:59       0
2017-02-01 07:00:00       0
Name: class, Length: 21474, dtype: Int16, metadata={'file_name': PosixPath('0/WELL-00001_20170201010207.parquet'), 'event_class': 0, 'event_type': 'real'})

What is in the "signal" key?

In [6]:
ds[0].signal

,ABER-CKGL,ABER-CKP,ESTADO-DHSV,ESTADO-M1,ESTADO-M2,ESTADO-PXO,ESTADO-SDV-GL,ESTADO-SDV-P,ESTADO-W1,ESTADO-W2,...,P-PDG,PT-P,P-TPT,QBS,QGL,T-JUS-CKP,T-MON-CKP,T-PDG,T-TPT,state
timestamp,,,,,,,,,,,,,,,,,,,,,
2017-02-01 01:02:07,NaN,NaN,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,NaN,10074540.0,NaN,0.0,84.64463,NaN,0.0,119.0781,<NA>
2017-02-01 01:02:08,NaN,NaN,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,NaN,10074540.0,NaN,0.0,84.63828,NaN,0.0,119.0781,<NA>
2017-02-01 01:02:09,NaN,NaN,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,NaN,10074540.0,NaN,0.0,84.63194,NaN,0.0,119.0781,<NA>
2017-02-01 01:02:10,NaN,NaN,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,NaN,10074540.0,NaN,0.0,84.62558,NaN,0.0,119.0781,<NA>
2017-02-01 01:02:11,NaN,NaN,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,NaN,10074540.0,NaN,0.0,84.61923,NaN,0.0,119.0781,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-02-01 06:59:56,NaN,NaN,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,NaN,10014690.0,NaN,0.0,83.44021,NaN,0.0,119.0453,0
2017-02-01 06:59:57,NaN,NaN,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,NaN,10014690.0,NaN,0.0,83.45413,NaN,0.0,119.0452,0
2017-02-01 06:59:58,NaN,NaN,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,NaN,10014690.0,NaN,0.0,83.46806,NaN,0.0,119.0451,0
2017-02-01 06:59:59,NaN,NaN,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,NaN,10014690.0,NaN,0.0,83.48199,NaN,0.0,119.0450,0
2017-02-01 07:00:00,NaN,NaN,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,NaN,10014690.0,NaN,0.0,83.49591,NaN,0.0,119.0449,0

Let's see the ids of the classes that we have in our loaded dataset:

In [7]:
set_of_labels = set()
for event in ds:
    set_of_labels = set_of_labels.union(event.label.unique())
set_of_labels

{np.int16(0), np.int16(4), <NA>}

## Customizable label selection

Let's reload the dataset ommiting the target column:

In [8]:
ds = ParquetDatasetConfig(path=dataset_path, target_column=None).build()

2026-04-06 13:18:29,290 | INFO | ThreeWToolkit.dataset.parquet_dataset | Dataset found at ../../dataset
2026-04-06 13:18:29,291 | INFO | ThreeWToolkit.dataset.parquet_dataset | Validating dataset integrity...
2026-04-06 13:18:29,292 | INFO | ThreeWToolkit.dataset.parquet_dataset | Dataset integrity check passed!

We expect not to have the "label" key.

In [9]:
ds[0].label

The signal should contain 'class' column:

In [10]:
ds[0].signal

,ABER-CKGL,ABER-CKP,ESTADO-DHSV,ESTADO-M1,ESTADO-M2,ESTADO-PXO,ESTADO-SDV-GL,ESTADO-SDV-P,ESTADO-W1,ESTADO-W2,...,PT-P,P-TPT,QBS,QGL,T-JUS-CKP,T-MON-CKP,T-PDG,T-TPT,class,state
timestamp,,,,,,,,,,,,,,,,,,,,,
2017-02-01 01:02:07,NaN,NaN,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,NaN,10074540.0,NaN,0.0,84.64463,NaN,0.0,119.0781,<NA>,<NA>
2017-02-01 01:02:08,NaN,NaN,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,NaN,10074540.0,NaN,0.0,84.63828,NaN,0.0,119.0781,<NA>,<NA>
2017-02-01 01:02:09,NaN,NaN,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,NaN,10074540.0,NaN,0.0,84.63194,NaN,0.0,119.0781,<NA>,<NA>
2017-02-01 01:02:10,NaN,NaN,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,NaN,10074540.0,NaN,0.0,84.62558,NaN,0.0,119.0781,<NA>,<NA>
2017-02-01 01:02:11,NaN,NaN,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,NaN,10074540.0,NaN,0.0,84.61923,NaN,0.0,119.0781,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-02-01 06:59:56,NaN,NaN,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,NaN,10014690.0,NaN,0.0,83.44021,NaN,0.0,119.0453,0,0
2017-02-01 06:59:57,NaN,NaN,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,NaN,10014690.0,NaN,0.0,83.45413,NaN,0.0,119.0452,0,0
2017-02-01 06:59:58,NaN,NaN,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,NaN,10014690.0,NaN,0.0,83.46806,NaN,0.0,119.0451,0,0
2017-02-01 06:59:59,NaN,NaN,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,NaN,10014690.0,NaN,0.0,83.48199,NaN,0.0,119.0450,0,0
2017-02-01 07:00:00,NaN,NaN,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,NaN,10014690.0,NaN,0.0,83.49591,NaN,0.0,119.0449,0,0

-------

## Event type splitting

Defining 2 types of events: drawn and simulated

In [11]:
event_types = ["drawn", "simulated"]

In [12]:
ds = ParquetDatasetConfig(path=dataset_path, event_type=event_types).build()

print("--------------------------------")
print(f"Filtering events of types {event_types}, there are {len(ds)} events")

2026-04-06 13:18:29,461 | INFO | ThreeWToolkit.dataset.parquet_dataset | Dataset found at ../../dataset
2026-04-06 13:18:29,462 | INFO | ThreeWToolkit.dataset.parquet_dataset | Validating dataset integrity...
2026-04-06 13:18:29,464 | INFO | ThreeWToolkit.dataset.parquet_dataset | Dataset integrity check passed!

--------------------------------
Filtering events of types ['drawn', 'simulated'], there are 1109 events

Only real events now:

In [13]:
event_types = ["real"]
ds = ParquetDatasetConfig(path=dataset_path, event_type=event_types).build()

print("--------------------------------")
print(f"Filtering events of types {event_types}, there are {len(ds)} events")

2026-04-06 13:18:29,517 | INFO | ThreeWToolkit.dataset.parquet_dataset | Dataset found at ../../dataset
2026-04-06 13:18:29,518 | INFO | ThreeWToolkit.dataset.parquet_dataset | Validating dataset integrity...
2026-04-06 13:18:29,519 | INFO | ThreeWToolkit.dataset.parquet_dataset | Dataset integrity check passed!

--------------------------------
Filtering events of types ['real'], there are 1119 events

------

## Event class splitting

We can select any combination of class events.

First, let's see how many events the whole dataset has.

In [14]:
# If no target class is provided (equivalent to `target_class=None`), all classes are loaded
ds = ParquetDatasetConfig(path=dataset_path).build()

print("--------------------------------")
print(f"Loading all classes, there are {len(ds)} events")

2026-04-06 13:18:29,569 | INFO | ThreeWToolkit.dataset.parquet_dataset | Dataset found at ../../dataset
2026-04-06 13:18:29,570 | INFO | ThreeWToolkit.dataset.parquet_dataset | Validating dataset integrity...
2026-04-06 13:18:29,571 | INFO | ThreeWToolkit.dataset.parquet_dataset | Dataset integrity check passed!

--------------------------------
Loading all classes, there are 2228 events

Now, let's select only events of one class (4):

In [15]:
# Only loading events from class 4
target_class = [4]
ds_config = ParquetDatasetConfig(path=dataset_path, target_class=target_class).build()

print("--------------------------------")
print(f"Filtering events of class {target_class}, there are {len(ds_config)} events")

2026-04-06 13:18:29,620 | INFO | ThreeWToolkit.dataset.parquet_dataset | Dataset found at ../../dataset
2026-04-06 13:18:29,621 | INFO | ThreeWToolkit.dataset.parquet_dataset | Validating dataset integrity...
2026-04-06 13:18:29,622 | INFO | ThreeWToolkit.dataset.parquet_dataset | Dataset integrity check passed!

--------------------------------
Filtering events of class [4], there are 343 events

Of 2 classes (0, 4):

In [16]:
target_class = [0, 4]
ds_config = ParquetDatasetConfig(path=dataset_path, target_class=target_class).build()

print("--------------------------------")
print(f"Filtering events of class {target_class}, there are {len(ds_config)} events")

2026-04-06 13:18:29,675 | INFO | ThreeWToolkit.dataset.parquet_dataset | Dataset found at ../../dataset
2026-04-06 13:18:29,677 | INFO | ThreeWToolkit.dataset.parquet_dataset | Validating dataset integrity...
2026-04-06 13:18:29,678 | INFO | ThreeWToolkit.dataset.parquet_dataset | Dataset integrity check passed!

--------------------------------
Filtering events of class [0, 4], there are 937 events

-------

## File list splitting

We can use a list to select loaded events. This is useful for customized train/val/test splitting.

In [17]:
split = [
    "6/SIMULATED_00012.parquet",
    "6/SIMULATED_00049.parquet",
    "0/WELL-00001_20170201010207.parquet",
    "4/WELL-00001_20170316110203.parquet",
]

In [18]:
# To get only files in split, we need to set split="list"
ds = ParquetDatasetConfig(path=dataset_path, split="list", file_list=split).build()
print("--------------------------------")
print(f"Loading files in split, there are {len(ds)} events")

2026-04-06 13:18:29,748 | INFO | ThreeWToolkit.dataset.parquet_dataset | Dataset found at ../../dataset
2026-04-06 13:18:29,749 | INFO | ThreeWToolkit.dataset.parquet_dataset | Validating dataset integrity...
2026-04-06 13:18:29,750 | INFO | ThreeWToolkit.dataset.parquet_dataset | Dataset integrity check passed!

--------------------------------
Loading files in split, there are 4 events

In [19]:
ds[0].signal

,ABER-CKGL,ABER-CKP,ESTADO-DHSV,ESTADO-M1,ESTADO-M2,ESTADO-PXO,ESTADO-SDV-GL,ESTADO-SDV-P,ESTADO-W1,ESTADO-W2,...,P-PDG,PT-P,P-TPT,QBS,QGL,T-JUS-CKP,T-MON-CKP,T-PDG,T-TPT,state
timestamp,,,,,,,,,,,,,,,,,,,,,
2018-04-01 18:45:12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24065160.0,NaN,1.662989e+07,NaN,NaN,87.216250,92.587820,NaN,NaN,0
2018-04-01 18:45:13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24065160.0,NaN,1.662990e+07,NaN,NaN,87.216250,92.587820,NaN,NaN,0
2018-04-01 18:45:14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24065160.0,NaN,1.662990e+07,NaN,NaN,87.216250,92.587810,NaN,NaN,0
2018-04-01 18:45:15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24065160.0,NaN,1.662990e+07,NaN,NaN,87.216240,92.587810,NaN,NaN,0
2018-04-01 18:45:16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24065160.0,NaN,1.662989e+07,NaN,NaN,87.216240,92.587810,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-04-02 02:15:06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,28374390.0,NaN,2.152077e+07,NaN,NaN,74.687747,82.148137,NaN,NaN,0
2018-04-02 02:15:07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,28374390.0,NaN,2.152077e+07,NaN,NaN,74.687721,82.148111,NaN,NaN,0
2018-04-02 02:15:08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,28374390.0,NaN,2.152077e+07,NaN,NaN,74.687683,82.148073,NaN,NaN,0
2018-04-02 02:15:09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,28374390.0,NaN,2.152077e+07,NaN,NaN,74.687654,82.148044,NaN,NaN,0
2018-04-02 02:15:10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,28374390.0,NaN,2.152077e+07,NaN,NaN,74.687626,82.148008,NaN,NaN,0